<?php
return array (
  'company/shebei' => '',
  'company/shebeijixie' => '',
  'company/xys_blue' => '',
  'company/xys_lvse' => '',
  'company/xys_qiye1' => '',
  'company_mobile/default' => '',
  'news/china' => '',
  'news/default' => '',
  'news/lanse' => '',
  'news/lvse' => 'zhizhuchi.cm',
  'news/xxfseo01' => '',
  'news/xxfseo02' => '',
  'news/xxfseo03' => '',
  'news/xxfseo04' => '',
  'news/xxfseo05' => '',
  'news/xxfseo06' => '',
  'news/xxfseo07' => '',
  'news/xxfseo08' => '',
  'news/xxfseo09' => '',
  'news/xxfseo10' => '',
  'news/xxfseo11' => '',
  'news_mobile/default' => '',
  'news_mobile/lansem' => '',
  'news_mip/mip01' => '',
  'news_mip/mip02' => '',
  'news_mip/mip03' => '',
  'news_mip/mip04' => '',
  'news_mip/mip05' => '',
  'video/movie' => '',
  'bbs/xiuno' => '',
);
?>